---
title: "ClusterSubSet"
output: html_document
---

```{r,eval=FALSE}
library(crypto)

will_i_get_rich <- getCoins(start_date = '20170907', end_date = '20180430')
```



```{r}

Bitcoin <- subset(will_i_get_rich,will_i_get_rich$ranknow == 1 )

Ethereum <- subset(will_i_get_rich,will_i_get_rich$ranknow == 2 )

Ripple <- subset(will_i_get_rich,will_i_get_rich$ranknow == 3 )

Bitcoin Cash <- subset(will_i_get_rich,will_i_get_rich$ranknow == 4 )

EOS <- subset(will_i_get_rich,will_i_get_rich$ranknow == 5 )

Cardano <- subset(will_i_get_rich,will_i_get_rich$ranknow == 6 )

Stellar <- subset(will_i_get_rich,will_i_get_rich$ranknow == 7 )

Litecoin <- subset(will_i_get_rich,will_i_get_rich$ranknow == 8 )

TRON <- subset(will_i_get_rich,will_i_get_rich$ranknow == 9 )

NEO <- subset(will_i_get_rich,will_i_get_rich$ranknow == 10 )

IOTA <- subset(will_i_get_rich,will_i_get_rich$ranknow == 11 )

Monero <- subset(will_i_get_rich,will_i_get_rich$ranknow == 12 )

Dash <- subset(will_i_get_rich,will_i_get_rich$ranknow == 13 )

NEM <- subset(will_i_get_rich,will_i_get_rich$ranknow == 14 )

Tether <- subset(will_i_get_rich,will_i_get_rich$ranknow == 15 )
```







```{r}
ub <- subset(will_i_get_rich,will_i_get_rich$ranknow == 1) 
name <- ub %>%
  summarise(strings = toString(unique(name)))
as.character(name[1,])
```

```{r}
clean <- function(data,r){
  for i in r {
    sub <- subset(data,data$ranknow == i)
    price <- sub$close
    name <- sub %>%
    summarise(strings = toString(unique(name)))
    
    
    eval(as.character(name[1,])
    
    
frame1 <-data.frame(Date=As.Date(sub$Date),
                     eval(as.character(name[1,])=as.numeric(sub$close))    
frame2 <- sub$date    
frame3 <- merge(p_text,p_text2) 
    
  }
  
  
  
  
  
  
  
  
}
  
  
  
```






